### ISSUE TITLE
Ubuntu icon theme workflow 

### ISSUE THREAD

**Issue by meetdilip** [ScreamingTaco/inkscape_app_icon_generator#1]
Hi,

https://gitlab.com/inkscape/inbox/issues/1248

As you can see from the Gitlab issue above, Ubuntu icon themes need SVGs to be exported as SVGs in various sizes. Say I draw on a 24x24 canvas, I will need 16x16, 32x32, 64x64, 128x128, 512x512 etc as the canvas size.

It takes hours to do the resize for a proper icon theme. If we can draw one SVG and then export it to different canvas sizes as SVG, that will be a great thing for Inkscape. Considering you have done a great addon here, will it be possible for you to attend this issue when you have time ? 

Thanks.

**Comment by ScreamingTaco** [comment]
Hmmm. Something doesn't seem quite right. The whole point of SVGs is that they are the same quality at any resolution, and thus can produce PNGs of any size without loss of quality. Are you wanting the extension to output all the required PNG sizes?

**Comment by meetdilip** [comment]
@ScreamingTaco Many thanks for the reply. Icon themes like Papirus use SVG instead of PNG for various sizes. The canvas size vary from 16, 32, 48, 64, 128, 256, 512 etc. The latest big ones are due to some changes in how Gnome deal with icons. One big SVG for all, something like that. But if you take a look at Papirus Icon Theme repo, you can see these different canvas sizes in uses just like PNG.

I think they have some script to resize them, not sure. But if someone without knowledge of creating script wants to add a single modification to it locally will have to resize the canvas every time to get it right. It has importance both in local editing as well as in commercial packs where we need to use different canvas size. 

I hope I explained well. Let me know if you need any other info. :)

**Comment by ScreamingTaco** [comment]
Sorry for the ultra-late response. Based on the gitlab link you provided, it looks like this issue is closed now. If not, feel free to reopen and I'll look into it (I'm trying to be more active in maintaining this project).
